title: "ZyntraBOT – Discord Security 2025"
description: "ZyntraBOT: 2025 güvenlik odaklı Discord botu. Guard, anti-nuke, webhook koruma, loglama ve çoklu dil desteği."

baseurl: "/zyntra-seo"
url: "https://zyntrabot.github.io"

theme: minima
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

author:
  name: ZyntraBOT
  website: https://zyntrabot.xyz
  discord: https://discord.gg/mvkywr753k

# ⭐ Banner ayarı
banner:
  enabled: true
  image: "/zyntra-seo/assets/images/banner.png"
  alt: "ZyntraBOT Cyberpunk Neon Banner"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

include:
  - googlebad0618b9dcbe2e0.html
